[workspace]
members = ["contracts/spore-warriors", "game/core", "game/generated", "tests/game", "tests/contracts"]

[profile.release]
overflow-checks = true
strip = true
opt-level = 's'
lto = true
codegen-units = 1
